/*
 * This source file was generated by the Gradle 'init' task
 */
package com.LegMeat.rbo.GUI;

import com.LegMeat.rbo.Backend.Video;
import com.LegMeat.rbo.Exceptions.InvalidFileTypeException;

import java.util.Calendar;
import java.util.Date;

public class App {
    public static void main(String[] args) {
        // hardcoded file (inc. start and end time) for now
        try {
            Video testVid = new Video("Problem Demonstration.mkv",
                    new Date(2025, Calendar.JUNE, 19, 1, 32, 52),
                    new Date(2025, Calendar.JUNE, 19, 1, 37, 52),
                    "C:\\Users\\OPGam\\Videos\\Solo Progressions");
            System.out.println(testVid.getData());
        } catch (InvalidFileTypeException e) {
            System.out.println(e.getMessage());
        }

    }
}
